### ISSUE TITLE
Fepois: More rigorous tests for separation

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#457] opened 2024-05-30 11:22 UTC
**Context**

In alignment with `fixest`, `pyfixest` currently only implements a very basic check for separation. 

PyFixest currently implements the most basic separation check, which is equivalent to ppmlhdfe's [separation(fe)](https://github.com/sergiocorreia/ppmlhdfe/blob/master/guides/separation_primer.md). 

Ppmlhdfe implements three more separation checks; it would be nice if `fepois()` would support some of them. 

For a primer on separation, see the [primer on separation ](https://github.com/sergiocorreia/ppmlhdfe/blob/master/guides/separation_primer.md) by the ppmlhdfe team. 

**To Do:** 

- implement additional separation checks for the [check_for_separation](https://github.com/py-econometrics/pyfixest/blob/734a21c34a56a88ba12b0fa26cd3ed0e8c24bd51/pyfixest/estimation/fepois_.py#L315) function. 
- Allow users to specify separation checks via the `fepois` and `Fepois` interfaces.

**Comment by leostimpfle** [comment] 2024-06-07 16:57
I'd be interested in working on this

**Comment by leostimpfle** [comment] 2024-06-07 17:12
Yes, seems sensible to do it method by method. I was thinking of initially focussing on `ir` (*iterative rectifier*) because it is recommended in combination with `fe` for regressions with many high-dimensional effects.

**Comment by leostimpfle** [comment] 2024-10-24 06:14
With #660 the user can specify `separtion_checks` for `fepois`. Currently, there are two checks implemented: the iterative rectifier `ir` and the original `fe` check.

`ppmlhdfe` implements two further methods:

- [`simplex`](https://github.com/sergiocorreia/ppmlhdfe/blob/master/guides/separation_primer.md#ppmlhdfe-separationsimplex): does not handle separation arising from fixed effects (which is arguably `pyfixest's` main use case)
- [`mu`](https://github.com/sergiocorreia/ppmlhdfe/blob/master/guides/separation_primer.md#ppmlhdfe-separationmu): a simple heuristic (if `y=0` and `exp(xb)` is also very close to zero, then the observations are likely separated)

My understanding is that `simplex` is less relevant for `pyfixest` as it doesn't cover separation arising from fixed effects and that `mu` is a nice to have but much less powerful than the iterative rectifier.

Would it therefore make sense to close this issue and open two separate issues for the implementation of `simplex` and `mu` @s3alfisc ?

**Comment by s3alfisc** [comment] 2024-10-24 17:01
Yes, I think we can close this - I think with the two separation tests we have, we're actually covered really well =)

**Closed** 2024-10-24 17:02 UTC
Labels: enhancement, good first issue
